name: lukha-hyprland-nvidia
description: ublue images for wayland compositors
base-image: ghcr.io/ublue-os/base-nvidia
image-version: 40

stages:
  - name: eww
    from: docker.io/library/rust:1.76.0-slim
    modules:
      - type: script
        scripts: 
          - rustdependencies.sh

modules:
  - type: copy
    from: eww
    src: /tmp/eww/target/release/eww
    dest: /usr/bin/
  - from-file: sddm-packages.yml
  - from-file: common-packages.yml
  - from-file: common-flatpaks.yml
  - from-file: hyprland-packages.yml
  - from-file: hyprland-files.yml
  - from-file: 1password-package.yml
  - from-file: common-files.yml
  - from-file: common-scripts.yml
  - from-file: hyprland-scripts.yml  
  - from-file: sddm-scripts.yml
  - type: wayblue-signing
  - from-file: sddm-systemd.yml
