---
name: Build ISOs

on:
  workflow_dispatch:
  workflow_call:

env:
  REGISTRY_USER: levitrammell
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/levitrammell

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-iso
  cancel-in-progress: true

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build ISO
        run: |
          mkdir ./iso-output
          sudo docker run --rm --privileged --volume ./iso-output:/build-container-installer/build --volume /home/runner/.docker/config.json:/docker-config.json --pull=always \
          ghcr.io/jasonn3/build-container-installer:latest \
          REGISTRY_AUTH_FILE=/docker-config.json \
          IMAGE_REPO=${{ env.IMAGE_REGISTRY }} \
          IMAGE_NAME=lukha-nvidia \
          IMAGE_TAG=latest
      # - name: Build ISO
      #   uses: jasonn3/build-container-installer@main
      #   id: build
      #   with:
      #     image_name: lukha-nvidia
      #     image_repo: ghcr.io/levitrammell
      #     image_tag: 40
      #     version: 40
      #     variant: base-main
      #     iso_name: lukha-40.iso
      #     secure_boot_key_url: "https://github.com/ublue-os/akmods/raw/main/certs/public_key.der"
      #     enrollment_password: "ublue-os"
      #     web_ui: true
      - name: Upload ISO as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ./iso-output/deploy.iso
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
